### ISSUE TITLE
Add async loading

### ISSUE THREAD

**Issue by ssebs** [klinker-apps/pulse-sms-web#79]
It would be nice if the extension (or page) loaded a loading bar or something, then loads the data.

Currently, when I click on the extension to view my messages, it freezes chrome for a second.

Example: 

![gif](https://i.imgur.com/gUUDT1E.gif)

Thanks!

**Comment by ssebs** [comment]
The website itself does the same thing though, it takes a second or two to load. During that time it just hangs while loading.

I'll have to find some time and see if I can submit a PR.

**Comment by Serubin** [comment]
This isn't an issue with the web app. I did some review, the web app transfers approximately 100kb uncached. On a 1mbit connection, the web app will have first render at 1.1 seconds with no caching and .2 seconds with caching.

It's possible the web app is loading slow for you, for whatever reason (though we have improved loading speed in the last 6 months), but ultimately this needs to be fixed in the chrome extension code.
